_target_: utils.llm_client.openai.OpenAIClient

model: gpt-4o-mini # LLM model (the ATSP benchmark standardises on this)
temperature: 1.0  # temperature for chat completion
api_key: ${oc.env:OPENAI_API_KEY,null}
